### ISSUE TITLE
Better support for django-extensions

### ISSUE THREAD

**Issue by mjl** [feincms/feincms#546]
django-extensions has a "shell_plus" management command that automatically imports all models so you don't have to. However, this fails with all content types:

    Failed to import 'PageTagIndexContent' from 'feincms.module.page.models' reason: 'module' object has no attribute 'PageTagIndexContent'
    Failed to import 'PhotoGalleryContent' from 'feincms.module.page.models' reason: 'module' object has no attribute 'PhotoGalleryContent'
    Failed to import 'RichTextContent' from 'feincms.module.page.models' reason: 'module' object has no attribute 'RichTextContent'

Should we try to register those names or will that bite us in the behind as such registrations already did (there are some issues for that)?

**Comment by matthiask** [comment]
@mjl noch aktuell?

**Comment by mjl** [comment]
Yes, it doesn't work with the newest feincms/django_extensions, so no change there. Also, I notice that the module is wrong -- `RichTextContent` is not in `feincms.module.page.models`, so that is really the problem, not the registration from #528. 

Can the module name be overridden somehow (no idea without diving into it)?

**Comment by matthiask** [comment]
Right now that's not possible (https://github.com/feincms/feincms/blob/8c1754a7083d3ff26fbf4efa67bb25df26fc81ec/feincms/models.py#L510)

The rationale for putting it into the same module as the base model is that most of the time there exists only one base model per Django app, which allows us to easily reuse content types for multiple base models inside the same project without renaming the resulting class (PageRichTextContent, EntryRichTextContent, ArticleRichTextContent). It does not matter too much, because django-extensions would not be able to import PageRichTextContent either...

**Comment by matthiask** [comment]
... maybe django-extensions should be patched to not crash and burn when importing a model class fails for some reason?

**Comment by mjl** [comment]
Ah I see. On further thoughts, those (base) models are rarely needed anyway, so there is not much point in having them imported in the first place.

django-extensions just throws those warnings and then chugs on, so there is no real harm done.

I'm closing that issue for now as it's more academic than of any practical concern.
