### ISSUE TITLE
Update docs for the new application content syntax

### ISSUE THREAD

**Issue by sbaechler** [feincms/feincms#589]
Apparently there is a new syntax for the `Page.create_content_type(ApplicationContent)` and `app_reverse` methods.
However, it is not mentioned in the docs yet.

**Comment by matthiask** [comment]
Not sure what you are referring to. I don't recall changing anything in this area recently?

**Comment by sbaechler** [comment]
Applications are now referred by their name:

    Page.create_content_type(
        ApplicationContent,
        APPLICATIONS=(
            ('contest', _('Contest'), {
                'urls': 'contest.urls',
            }),
        ))

**Comment by matthiask** [comment]
The `urls` parameter is documented since FeinCMS 1.3 and implemented / supported since FeinCMS 1.2. You do not *have* to do it this way, but it's much easier to exchange the URLconf module (i.e. replace `registration.urls` with `myapp.registration_urls` or something like that)

https://github.com/feincms/feincms/commit/556d2690aee5a2dadfbcfefe07926dae35276512

**Comment by sbaechler** [comment]
Indeed. Apologize. I have never scrolled this far down in the documentation.

**Comment by matthiask** [comment]
There's no need to apologize :-)

**Comment by mjl** [comment]
> There's no need to apologize :-)

  Right, if the docs are so badly written that you stopped reading midway, we should work on the docs :-)
