### ISSUE TITLE
Inlines in content types?

### ISSUE THREAD

**Issue by paramono** [feincms/feincms#614]
I would like to add some inlines for content types, and, as I understand, content types in FeinCMS are handled as inlines already. Since Django does not support nested inlines out of the box, this requires some 3rd party solution to make it work.

I've encountered some of these:
https://github.com/s-block/django-nested-inline
https://github.com/theatlantic/django-nested-admin
https://github.com/BertrandBordage/django-super-inlines

Which FeinCMS models will I need to rewrite in order to make nested inlines work? Will it be enough to extend ItemEditor, inheriting some of the 3rd party models for nested inline handling?

**Comment by valmynd** [comment]
you may not need to rewrite anything at all. you could look at how the "Section" contenttype is implemented, as it is using Inlines:

see https://github.com/feincms/feincms/blob/master/feincms/content/section/models.py

unfortunately it is not possible to subclass SectionContent, but for my needs I just copied the hole thing and changed the parts I wanted changed and it worked nicely. It did also work to use django's StackedInline instead FeinCMSInline when I tried that.

**Comment by paramono** [comment]
This is not exactly the same thing.
I've seen how Section content type is implemented, and I also have seen a similar approach in [form_designer plugin](https://github.com/feincms/form_designer/blob/master/form_designer/models.py). 

In case of section, you can edit title, richtext, and mediafile. Neither of these are inlines, they're just Fields; the special case is mediafile, though, as it is a foreignkey. To make it work, there is a raw_id_fields attribute defined SectionContentInline. It allows you to choose an existing mediafile by id from a popup window. But this is not a nested inline, it doesn't allow you to change Mediafile's fields on the fly on Page admin.

Imagine you have a Container and Element models. Each element has a foreign key to a Container. Each container may have an arbitrary number of elements. You want to make a content type for Container model, to be able to add and remove its Elements in Page admin, and to fill in every field for every Element from Page admin. But you can't. 

The only working solution so far is to define a ContainerContent with a ForeignKey to Container. Then, on Page admin you create ContainerContent, and assign a foreign key to new or existing Content; all the relations between Content and Elements you make outside of Page admin.

While there are many advantages in that approach, sometimes you need quick and simply nesting for content types. I was interested whether it is possible to do so without interfering too much with the way feincms works.

**Comment by matthiask** [comment]
Thanks for the report. 

The biggest stumbling block for implementing such a thing is that you have to disable and re-enable the dynamic behavior inside a content block when reordering content, or when moving content to another region. That's the raison d'être for the richify/poorify functionality (http://feincms-django-cms.readthedocs.org/en/latest/contenttypes.html#other-rich-text-libraries). 

A minor problem is that we replace the inline template with our own, and those inlines-in-inlines apps have to do the same (ex. https://github.com/s-block/django-nested-inline/tree/master/nested_inline/templates/admin/edit_inline). This simply does not work well.

I have been tinkering a bit with massively simplifying the item editor code in an external app (https://github.com/matthiask/django-content-editor) — implementing the missing functionality would probably be much simpler in django-content-editor than in FeinCMS proper, because d-c-e is a much slimer add-on to django.contrib.admin than the FeinCMS ItemEditor... 

So maybe, if you want this, try implementing it using django-content-editor instead. I'm very interested in any results you get. Thanks in advance!

**Comment by matthiask** [comment]
Addendum: Some preliminary documentation for django-content-editor is here: https://github.com/matthiask/django-content-editor/blob/master/docs/index.rst

**Comment by matthiask** [comment]
As I said above this should be much much easier with django-content-editor. It could even work out of the box since django-content-editor uses flex-ordering of fieldsets.
