### ISSUE TITLE
Migrating from 1.10.0 to 1.12.1

### ISSUE THREAD

**Issue by barseghyanartur** [feincms/feincms#653]
Are there any notes on migrating from 1.10.0 to 1.12.1?

It all seems to work, but I noticed that ``fein_tree.js`` and ``fein_tree.css`` have been removed, while they are used in the project I work on. I wonder, if there are more of such changes I would consider.

But, at first, any suggestions on how to deal with removed ``fein_tree`` assets (except adding old ones to the static files)?

**Comment by matthiask** [comment]
The two assets are still available as `tree_editor.css` and `tree_editor.js`.

Apart from that it seems to me that most changes aren't backwards incompatible, except for the TemplateContent change which requires an explicit list of template names since 1.12: http://feincms-django-cms.readthedocs.io/en/latest/releases/1.12.html#template-content-requires-explicit-list-of-templates and of course removed features such as feincms.content.comments, feincms.content.rss, feincms.module.blog, frontend editing etc.

You'll get a few warnings of course because some preferred import paths have changed, but backwards compatibility import shims should alleviate the pain a bit. I wouldn't expect many problems upgrading (in fact it mostly "just works" for us as well)

**Comment by barseghyanartur** [comment]
@matthiask:

As I understand, the following replacements have been made:

- jquery.cookie.js -> js.cookie.js
- toolbox.js merged into tree_editor.js (**unsure**)
- ie_compat.js removed.

Could you confirm?

If all above correct, I would write a couple of lines about it in the docs and make a pull request.

**Comment by matthiask** [comment]
js.cookie.js: Correct. jquery.cookie.js recommends switching: https://github.com/carhartl/jquery-cookie

ie_compat.js: Array.prototype.indexOf have been inlined into item_editor.js and tree_editor.js, the rest was unused 210964f470fac36ff6a3eeb56c2c125d7dd65b60

toolbox.js has been removed (resp. merged into fein_tree.js a long time ago ( e257af27bf9d62871a00abf1b49da63fcafa2ead / v1.8.4-28-ge257af2 )

Thanks!

**Comment by matthiask** [comment]
Closing; please reopen (or open a new issue) if there's still an open issue here. Thanks!
