### ISSUE TITLE
thumbnail not a valid template library

### ISSUE THREAD

**Issue by DylanYoung** [feincms/feincms#682]
```
Invalid template .../python2.7/site-packages/feincms/templates/content/filer/image.html: 'thumbnail' is not a registered tag library. Must be one of:
...
```

Should be `feincms_thumnail`?

**Comment by DylanYoung** [comment]
Could be an error with `django-compressor` as well, not certain.

**Comment by matthiask** [comment]
django-filer depends on easy-thumbnails which provides a `thumbnail` template tag library, because of this the default templates for django-filer's content types use easy-thumbnails.

Are you using django-compressor's offline compression feature? Is there a way to make django-compressor ignore unused templates?

**Comment by DylanYoung** [comment]
I don't believe there is; it's pretty naive.  In any case, glad to know the source of the warning and that it probably isn't an issue.  I'm going to close this out.  Sorry for the delayed reply :)
