### ISSUE TITLE
Feincms and Django 3.1

### ISSUE THREAD

**Issue by andrey-zubov** [feincms/feincms#689]
Feincms (version 1.18.0) build-in page modules (probably not only them) dont work with **Django 3.1.**

Duaring the doc (https://feincms-django-cms.readthedocs.io/en/latest/page.html#) "page" field in admin panel returns empty page.

**Temporary solution:**
uninstall django 3.1 and install django 3.0

**Comment by koriaf** [comment]
It's because new Django 3.1 admin panel has block `#main` and Feincms has block `#main` (as tabs) and the code
```
$(main_selector + " > div:visible, " + main_selector + " > fieldset:visible").hide();
```
hides the Django one as well. The best solution here is to prefix all feincms classes by something, although it's a non-trivial change. Or just exclude django3.1 `main` block by some extra rule.

**Comment by emilkjer** [comment]
We've realised this issue is causing the Django admin not working at all and commenting out that line of code solves it. 

`#main` is a generic termin that's likely to clash with other software-packages that has similar generic naming, where either making the selector more specific or prefixing could make sense from my perspective.

**Comment by koriaf** [comment]
I have it fixed for my case but there is no PR yet (need to keep it for a little more to see if something else breaks). https://github.com/koriaf/feincms/commits/master

feel free to test and merge these commits if you want.

**Comment by mjl** [comment]
> I have it fixed for my case but there is no PR yet (need to keep it 
> for a little more to see if something else breaks).

   Looks good. Though, while we're at it, should we hunt for more 
not-very-unique ids and classes? Did you notice any other potential 
collisions?

**Comment by koriaf** [comment]
there are some possible ones, but I don't have knowledge of it at all (not even using it directly), so I'm just afraid to do changes I don't understand :-)

**Comment by matthiask** [comment]
I think the changes in your fork are obviously correct until now. If you want to open a pull request I'll happily roll another release for this.

**Comment by emilkjer** [comment]
We're now running with a fork of your `master` branch @koriaf . Will report back here if encounter any issues.

**Comment by danpalmer** [comment]
@matthiask Any chance of getting this fix in to core? I think the editor is essentially unusable on Django 3.1 and above.

**Comment by matthiask** [comment]
Oh, I forgot to close this issue! Thanks for the reminder.

v1.20.0 (released in March) contains the fix.

**Comment by danpalmer** [comment]
@matthiask are you sure? We're seeing the same issue on Django 3.2 and FeinCMS 1.20.1.

**Comment by danpalmer** [comment]
Wait. Scratch that I found a template override on our end! Sorry for the false alarm.

**Comment by matthiask** [comment]
I'm relieved! 🥳

**Comment by mjl** [comment]
Just FYI, we rolled out a new CMS last week with all new FeinCMS/Django combo and I haven't heard anything about things that do not work; that just as an independent data point, looks good from my side!
