### ISSUE TITLE
FeinCMS and django-tinymce 4+ and TinyMCE 5, 6 ... 7 ?

### ISSUE THREAD

**Issue by jowan** [feincms/feincms#720]
FeinCMS's support for TinyMCE only goes up to version 4.

django-tinymce now supports TinyMCE 6. This includes new UI with AI and Accessibility plugins, making it modern web editor.

I have not been able to make FeinCMS 23.1.0 work with django-tinymce 4.1.0 using the previous methods that worked for  TinyMCE versions 3 to 4 as described in feincms/templates/admin/content/richtext/init_tinymce4.html

I can sort-of get it to work, but not with the FeinCMS content ajax elements of the form.

Do you intend on supporting TinyMCE 6 and django-tinymce 4+ ? and keeping it in sync with Django in general, or is it abandoned ?

Many thanks

**Comment by matthiask** [comment]
Hi @jowan 

I think the best would be to ship an updated `init_tinymce6.html` template or something? If I understand the tinyMCE API docs correctly, using `tinymce.init()` in the init and richify handler and `tinymce.remove()` in the poorify handler should work?

> I can sort-of get it to work, but not with the FeinCMS content ajax elements of the form.

Or maybe you already got so far, but the reordering doesn't work? The reordering requires move handlers which remove the editor before dragging and attach it again afterwards, see https://github.com/feincms/feincms/blob/a9cb72cd502adad8645bc276bab88dc9bd546192/feincms/templates/admin/content/richtext/init_tinymce4.html#L55-L65 -- the reason for this is that the DOM doesn't support moving nodes around without losing event handlers at this time. [This could change in the near future](https://github.com/whatwg/dom/pull/1307), but I don't know if the jQuery sortable libraries will be updated for this.

> Do you intend on supporting TinyMCE 6 and django-tinymce 4+ ? and keeping it in sync with Django in general, or is it abandoned ?

I wrote down my thoughts here https://406.ch/writing/the-future-of-feincms/ and despite the fact that this post is more than 6 years old it's still current. The only thing which has changed is that most of the sites we have are running on feincms3/django-content-editor instead of FeinCMS.

By the way, django-content-editor uses [flex ordering](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout/Ordering_flex_items) to avoid the poorify/richify problem -- nodes aren't actually moved around in the DOM, they are only reordered visually. This means that we can basically use all Django form field plugins without having to add our own handlers.

That being said, I'd be very happy if we found a way to keep FeinCMS working with newer tinyMCE versions.
